name: Generate Kotlin

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  generate-kotlin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: List directory structure before building
        run: ls -R

      - name: Generate Protos
        run: ./gradlew generateProtos

      - name: List directory structure after building
        run: ls -R

      - name: List generated Kotlin files for debugging
        run: ls -R lib/build/generated/source/wire/ || echo "Directory not found"

      - name: Upload generated Kotlin files
        uses: actions/upload-artifact@v4
        with:
          name: generated-kotlin-files
          path: lib/build/generated/source/wire/**/*.kt

      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          repository: 'ksharma-xyz/Kotlin-Proto'
          token: ${{ secrets.TOKEN }}

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: generated-kotlin-files
          path: ./generated

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.TOKEN }}
          branch-suffix: timestamp
          committer: Github Actions Bot <42103905+github-actions[bot]@users.noreply.github.com>
          author: Github Actions Bot <42103905+github-actions[bot]@users.noreply.github.com>
          commit-message: "Add generated Kotlin files $(date +'%Y-%m-%dT%H:%M:%S')"
          title: "Add generated Kotlin files $(timestamp)"
          body: "This PR adds the generated Kotlin files from the https://github.com/ksharma-xyz/Proto-API project."
          base: main
